#!/bin/bash
# scripts/quickstart.sh
# Holt: Instant Audit Demo
# Usage: curl -sL https://raw.githubusercontent.com/hearth-insights/holt/main/scripts/quickstart.sh | bash

set -e

GREEN='\033[0;32m'
TEAL='\033[0;36m' 
RED='\033[0;31m'
NC='\033[0m'

echo -e "${TEAL}::: HOLT SOVEREIGN ORCHESTRATION :::${NC}"

# Safety Check: Ensure we aren't already in a Git repository
if [ -d ".git" ]; then
    echo -e "${RED}Error: Current directory is already a Git repository.${NC}"
    echo "The quickstart script initializes a new git repository in the current directory."
    echo "Please run this script in a new, empty directory."
    exit 1
fi

echo "Initializing demonstration environment in current directory..."

# Check prerequisites
if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: docker is required.${NC}"
    exit 1
fi

# 1. Download Binaries
echo -e "${GREEN}1. Downloading Holt binaries...${NC}"

# Detect OS/Arch logic inlined from download-holt.sh
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"
case "$ARCH" in
    x86_64) ARCH="amd64" ;;
    aarch64|arm64) ARCH="arm64" ;;
esac

# Use release/download/latest pattern as verified
BASE_URL="https://github.com/hearth-insights/holt/releases/download/latest"
HOLT_BINARY="holt-$OS-$ARCH"
# Agent container is Linux-based, so we must download the Linux binary for pup
PUP_BINARY="holt-pup-linux-$ARCH"

mkdir -p bin
cd bin

echo "Fetching $HOLT_BINARY..."
if ! curl -f -L -o holt "$BASE_URL/$HOLT_BINARY"; then
    echo -e "${RED}Error: Failed to download holt binary.${NC}"
    exit 1
fi
chmod +x holt

echo "Fetching $PUP_BINARY..."
if ! curl -f -L -o holt-pup "$BASE_URL/$PUP_BINARY"; then
    echo -e "${RED}Error: Failed to download holt-pup binary.${NC}"
    exit 1
fi
chmod +x holt-pup

cd ..
echo "✓ Binaries installed to ./bin/"

# 2. Scaffold Configuration and Agent
echo -e "${GREEN}2. Scaffolding demo environment...${NC}"

# Create Agent Directory
mkdir -p agents/GitAgent

# Create Agent Run Script
cat > agents/GitAgent/run.sh <<'EOF'
#!/bin/sh
set -e
# Read input from stdin
input=$(cat)
echo "Git agent received input: $input" >&2

# Extract filename from payload using jq (default to audit_proof.txt if empty)
# The Goal artefact payload is the filename.
filename=$(echo "$input" | jq -r '.target_artefact.payload // "audit_proof.txt"')

echo "Creating file: $filename" >&2
cd /workspace

# Create the proof file
cat > "$filename" <<PROOF
AUDIT PROOF
Generated by Holt Agent
Timestamp: $(date -u)
PROOF

# Git commit
if [ -d ".git" ]; then
    git add "$filename"
    git commit -m "Agent generated proof: $filename"
    hash=$(git rev-parse HEAD)
else
    hash="no-git-repo"
fi

# Return result to FD 3
cat <<RESULT >&3
{
  "artefact_type": "CodeCommit",
  "artefact_payload": "$hash",
  "summary": "Created $filename"
}
RESULT
EOF
chmod +x agents/GitAgent/run.sh

# Create Dockerfile
# We COPY the pre-downloaded holt-pup binary into the image
cat > agents/GitAgent/Dockerfile <<EOF
FROM alpine:latest
RUN apk --no-cache add git ca-certificates jq
WORKDIR /app
# Copy the binary we downloaded
COPY holt-pup /app/pup
COPY run.sh /app/run.sh
RUN chmod +x /app/run.sh
# Configure git for the agent
RUN git config --global user.email "agent@holt.local" && \
    git config --global user.name "Holt Git Agent" && \
    git config --global --add safe.directory /workspace
ENTRYPOINT ["/app/pup"]
EOF

# Create holt.yml
cat > holt.yml <<EOF
version: "1.0"
orchestrator:
  image: "ghcr.io/hearth-insights/holt/holt-orchestrator:latest"
agents:
  GitAgent:
    role: "Git Agent"
    image: "example-git-agent:latest"
    command: ["/app/run.sh"]
    workspace:
      mode: rw
    bidding_strategy:
      type: "exclusive"
      target_types:
        - "GoalDefined"
services:
  redis:
    image: redis:7-alpine
EOF

# Create .gitignore
cat > .gitignore <<EOF
bin/
holt-demo-*
*.log
EOF

# 3. Build Agent Image
echo -e "${GREEN}3. Building agent container...${NC}"
# We need to copy holt-pup to the agent dir context for the build
cp bin/holt-pup agents/GitAgent/
# Build
(cd agents/GitAgent && docker build -t example-git-agent:latest . > /dev/null)
# Clean up the binary from agent source dir
rm agents/GitAgent/holt-pup

# 4. Initialize Git Repo
echo -e "${GREEN}4. Initializing git repository...${NC}"
git init > /dev/null
git add .
git commit -m "Initialize Holt demonstration" > /dev/null

# 5. Run Workflow
echo -e "${TEAL}::: SYSTEM ONLINE. EXECUTING WORKFLOW :::${NC}"
if ! "./bin/holt" up > holt_up.log 2>&1; then
    echo -e "${RED}Error starting Holt instance:${NC}"
    cat holt_up.log
    exit 1
fi

"./bin/holt" forage --goal "audit_proof.txt" > /dev/null

# Show Proof
echo -e "${TEAL}::: AUDIT TRAIL GENERATED :::${NC}"
echo "Waiting for agent to complete task..."
for i in $(seq 1 30); do
    if [ -f "audit_proof.txt" ]; then
        echo -e "${GREEN}Proof of Work verified!${NC}"
        ls -la audit_proof.txt
        break
    fi
    sleep 1
    echo -n "."
done
if [ ! -f "audit_proof.txt" ]; then
    echo -e "\n${RED}Proof file not found yet. Check logs:${NC}"
    "./bin/holt" logs GitAgent
fi

echo ""
echo -e "${GREEN}Demo environment ready!${NC}"
echo "You can now run holt commands directly:"
echo "  ./bin/holt watch"
echo "  ./bin/holt hoard"
echo "  ./bin/holt down  # to stop the system"
